### ISSUE TITLE
MalformedMessage: HIRMG is mandatory but missing.

### ISSUE THREAD

**Issue by fbrinker** [jschyma/open_fints_js_client#11]
Hallo Jens,

sehr schöne Library, werde sie mal ein wenig testen. Vielleicht kommt dann auch noch die ein oder andere Anpassung zustande, gefällt mir bis jetzt aber sehr gut. Bin nur über die obige Message etwas verwirrt. In meinem Fall rufe ich bei der DKB meine Konten ab. Habe dort 3 Konten liegen die ich normal als SEPA Konten abfragen kann.

Nach der Verbindung habe ich dann in `client.konten` die Konten liegen. Meine Idee war nun, diese mit einer  Schleife zu durchlaufen und dann für jedes Konto ein `client.MsgGetKontoUmsaetze` auszuführen. Allerdings geht das nur für ein Konto, danach geben die anderen die Error-Meldung `MalformedMessage: HIRMG is mandatory but missing.` zurück.

Grundsätzlich kein Problem, wenn ich das weiß, allerdings frage ich mich woher das kommt, da ich es nicht so ganz effizient finde immer neue Verbindungen aufbauen zu müssen. Ist das eine Sicherheits-Spezifikation des HBCI/FinTS, die ich nicht finden konnte, oder ein Verhalten der DKB?

Grüße

**Comment by jschyma** [comment]
Hallo

Erstmal vielen Dank für dein Interesse am OpenFinTSJSClient. Anpassungen sind jederzeit willkommen, stell einfach ein PullRequest. Solltest du weitere Fragen haben kannst du gerne wieder auf mich zu kommen.

Ich habe versucht deine Fragen zu beantworten, ich habe mich etwas weiter gefasst. Ich hoffe du kommst damit weiter. 

Zunächst ein paar Erläuterungen zum Thema FinTS, da ich nicht weiß wieweit du das Protokoll bereits kennst fange ich recht einfach an.
Zunächst musst du wissen was FinTS unter einem HBCI-Dialog, Nachricht, Segment, Datenelement, Datenelementgruppe, Auftrag verstehst:

(Infos hierzu findest du in folgendem [PDF](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/Gesamtdok_HBCI22.pdf)  im Glosar ab Seite(im folgenden immer PDF-Seiten angegeben) 12.

* **HBCI-Dialog:** Das ist der auf FinTS Ebene bestehende Kommunikationskanal zwischen Client(die FinTS Library) und Bank(Server). Allerdings nicht unbedingt im technischen Sinne der Verbindung sondern nur aus dem FinTS Protokoll, mehr dazu unten.
* **Nachricht:**  Sende- bzw. Empfangseinheit, die sich aus Segmenten zusammensetzt. Nachrichten haben einen Kopf mit einer Dialog-ID, welche die Zugehörigkeit zum Dialog herstellt. Ein Dialog wird von einem Client initiert mit mindestens einer Nachricht, inkl. der Kundenkennung + PIN, das wird durch die Methode client.EstablishConnection(..) durchgeführt und letztlich durch eine Nachricht entweder von der Bank(bei Fehlern) oder vom Client mit der Methode client.MsgEndDialog(..) beendet. Dazwischen können bliebig viele Nachrichten folgen. Es ist immer so, zunächst schickt der Client eine Nachricht an den Server und die Bank antwortet immer auf diese Nachricht. Eine andere Möglichkeit der Client schickt 2 Nachrichten oder die Bank 2 oder die Bank zuerst ist nicht möglich.
* **Segment:** Untereinheit einer Nachricht. Aufträge werden durch die Einfügung des entsprechenden Segments in eine Nachricht vom Client an die Bank realisiert. Eine Nachricht kann mehrere Segmente enthalten, auch Banknachrichten enthalten antwort Segmente, diese enthalten eine Referenznummer, die eine eindeutige Zuordnung an ein Segment aus der Anfragenachricht des Clients zulassen.
* **Datenelement, Datenelementgruppe:** Weitere Untereinheiten des Segments, welche dann spezielle Infos enthalten.

Weitere Infos speziell zum Thema Nachricht, Segement, Datenelement siehe S.22.
Auftrag:  Nutzdatensegment des Kunden an das Kreditinstitut, mit der ein Transaktions- oder Abholauftrag erteilt wird. D.h. in unserem Fall Umsätze für ein best. Konto abfragen.

## Nun ist es weiter wichtig folgendes zu wissen:

Wissenswert dabei ist, dass die ersten Versionen von HBCI(der Vorgänger von FinTS) zunächst so designed waren, dass die Kommunikation über einen TCP-Channel bzw. BTX/Datex-P hergestellt wurden. D.h. über ein Protokoll, welches Stateful ist und technisch nach einem Verbindungsaufbau bidirektionale Kommunikation zulässt. Die FINTS JS Library nutzt allerdings auf technischer Ebene eine andere Kommunikationsvariante, nämlich das Protokoll http über SSL. D.h. ein stateless protokoll, welches lediglich das einmalige Senden von Daten im HTTP Request vom Client zum Server und die einmalige Übermittlung einer Antwort zulässt, im http Response. Das heißt pro http Request wird eine neue TCP-Verbindung aufgebaut, von HTTP-Pipelining abgesehen. FinTS löst das ganze nun so, pro http-Request wird eine Nachricht versandt und im Response die dazugehörige Antwort-Nachricht. Da FinTS aber Stateful ist, wird dies über die oben besagte Dialog-ID im Nachrichtenkopf sichergestellt. Das heißt für jeden FinTS-Dialog, der mehr als 2 Nachrichten haben soll werden mehr als eine TCP-Verbindung im Laufe der Zeit aufgebaut.

Weitere Infos dazu findet sich im Kapitel "VIII.6 Tansportmedienspezifische Festlegungen" S.542.

##### Jetzt sind noch folgende eher dem eigentlichen FinTS Protokoll zuzuordnenden Informationen wichtig:

Das Segment HKKAZ dient dem Abrufen der Kontoumsätze(also das Segment zur Erteilung des Auftrags „Abholung der Umsätze“, alternativ gibt es auch noch das neuere Segment HCKAZ, welches allerdings nicht implementiert ist in der OpenFINTS Js Library. Das zugehörige Rückmelde Segment(das welches als Antwort von der Bank kommt) ist das HIKAZ. Damit sind die Bankparameterdaten zu diesem Element im Segment HIKAZS. Bankparameterdaten(BPD) sind eine Reihe von Segmenten, welche am Anfang der Initialisierung des Dialogs in der ersten Antwort Nachricht an den Client von der Bank übermittelt werden. Die BPD dienen dazu, dem Client mitzuteilen, welche Aufträge werden wie von der Bank unterstützt, weil hier gibt es große Unterschiede. Im Segment HIKAZS ist das 2. Element mit der Bezeichnung „Maximale Anzahl Aufträge“  versehen, dieses gibt an wie viele Aufträge von diesem Typ „Umsatzabfrage“ in einer Nachricht gestellt werden dürfen.

Mehr Infos dazu in einem [weiteren PDF](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf) auf der Seite 34.


# Nun zu deinen Fragen:
1. **Musst du mehrere Verbindungen aufbauen um die Umsätze für mehrere Konten abzurufen?**

Diese Frage muss ich differenzierter beantworten, je nachdem was du unter Verbindung verstehst:
*	Verbindung im Sinne von HBCI-Dialog

Du kannst in einem HBCI-Dialog so viele Aufträge erteilen wie du möchtest. Der Dialog beginnt in der Client-Library mit der Methode client.EstablishConnection(..) gibt der Callback kein error zurück, kann nun beliebig oft, die Methode client.MsgGetKontoUmsaetze(…)  aufgerufen werden. Allerdings sollte man darauf achten, dass der nächste Aufruf von client.MsgGetKontoUmsaetze(…) erst dann statt findet, wenn der letzte Callback zurückgerufen wurde = Sequenzielle Ausführung. D.h. es müsste so aussehen:
```javascript
client.EstablishConnection(function(error){
			if(error){
				console.log("Fehler: "+error);
			}else{
			client.MsgGetKontoUmsaetze(client.konten[0].sepa_data,null,null,function(error2,rMsg,data){
				client.MsgGetKontoUmsaetze(client.konten[1].sepa_data,null,null,function(error2,rMsg,data){
						client.MsgEndDialog(function(error,recvMsg2){
							// 6. Secure Daten im Objekt aus dem Ram löschen
							client.closeSecure();
							console.log("ENDE");
						});
					});
				});
			}
});
```
Ein Queeing wird von der Library nicht vorgenommen oder unterstützt, wäre aber nicht schlecht das zu implementieren. Bevor ich das implementiert habe würde ich dir die Library 'ASYNC' empfehlen mit folgender Methode [series](https://github.com/caolan/async#seriestasks-callback).

Du dachtest vielleicht, du musst jedes Mal neu mit client.EstablishConnection(..) usw. einen neuen Dialog aufbauen. Das ist nicht notwendig, zumindest sollte es das nicht sein, außer es ist irgendwo ein Fehler. Aus Sicherheitsgründen ist das auch nicht zu befürworten. Ehrlichgesagt wäre ich mit zu vielen Dialogen in kurzer Zeit sehr vorsichtig. Ich kann mir vorstellen, dass die Server der Banken dies eventuell als Angriff/Hacking oder ähnliches Werten, ähnlich wie bei einem zu oft falsch eingegebenen Passwort und dann womöglich noch dein Konto sperren.
*	Verbindung im Sinne von TCP-Verbindung bzw. HTTP-Request

Implementierst du diesen mehrfachen Aufruf der Umsätze während eines Dialogs wie oben dargestellt, werden technisch pro Aufruf eine Nachricht und damit ein http-Request, damit eine TCP-Verbindung aufgebaut. Dabei hat man logischerweise einen gewissen Overhead für jede Verbindung als würde man genau die gleiche Anzahl bytes über nur eine Verbindung schicken. Das FinTS Protokoll bietet hier in manchen Fällen eine Möglichkeit das Problem anzugehen. Dies ist aber nicht in der Library implementiert. Die Methode `client.MsgGetKontoUmsaetze(…)` erzeugt pro Aufruf eine Nachricht, die jeweils nur einmal den Auftrag, also das Segment HKKAZ, zum Abrufen der Umsätze für ein Konto enthält. Die Folge ist, dass auch immer ein neuer http-Request abgesetzt wird mit all seinen Folgen.

Nur ein Auftrag zum Abrufen der Umsätze pro Nachricht ist nach FinTS allerdings nicht zwingend. Theoretisch besteht die Möglichkeit unendlich viele HKKAZ Segmente in die Nachricht zu packen. Dies wird allerdings durch die bereits oben beschriebene Angabe in den Bankparameterdaten(BPD) im Segment HIKAZS begrenzt und durch eine weitere die Besagt wie viele Aufträge generell pro Nachricht verschickt werden können. Ich habe für die DKB mal nachgeschaut(für BLZ 12030000), die senden in ihren BPD die Zahl 3. Das heißt für die DKB wären theoretisch 3 Aufträge pro Nachricht möglich, es könnten also pro http-Request für 3 Konten die Umsätze gleichzeitig abgerufen werden.

Obwohl es das Protokoll hergibt mehrere Aufträge pro Nachricht zu versenden plädiere ich dafür es nicht zu implementieren und meine Gründe sind:
* Der Mehrfache Aufruf erzeugt zwar einen Overhead, dieser ist allerdings erst bei sehr vielen Anfragen wirklich von Bedeutung. Etwas mehr von Bedeutung dürfte der Zwang sein alles Sequenziell aufrufen zu müssen. Das ver-x-facht die Ausführung bei x Umsatzanfragen wahrscheinlich etwa. Trotzdem denke ich, dass bei 3 Konten oder auch 10 Konten die Abfrage noch unter 1 Sekunde stattfindet. Ich habe es jetzt allerdings nicht getestet.
* Ich habe bei verschiedenen Banken mir die BPD angeschaut und bei einigen ist es üblich nur ein Auftrag pro Nachricht zuzulassen. Das heißt in diesen Fällen würde diese Erweiterung gar nicht zum Tragen kommen.
* Manche Banken begrenzen die Antwortnachricht auf eine bestimmte Größe, wird diese Größe überschritten, muss der Client den Auftrag unter Angabe eines zuvor zurückgegebenen sogenannten Aufsetzpunktes neu stellen. In der Antwort Nachricht werden die weiteren Infos zurückgeliefert. Mit wachsender Anzahl Aufträge für weitere Konten pro Nachricht, ist das Größenlimit der Antwortnachricht schneller erreicht, es werden mehr Aufsetzpunktnachrichten erforderlich. Das kann soweit führen, dass der Effekt alles mit einer Nachricht zu holen gänzlich aufgehoben wird.
* Das Interface der Library würde sich verändern müssen, der Methode müsste auch mehrfache Kontos zulassen, der Callback müsste das Auslesen der Umsätze für mehrere Konten zulassen.
* Das ganze ordentlich zu implementieren, verkompliziert die Methode wesentlich und bedarf schon eines wesentlichen Aufwands.
* Das Auswerten von Fehlern wird wesentlich schwerer, weil die Nachricht verkompliziert wird.
* Alles in allem, lohnt es sich aus meiner Sicht nicht diese Möglichkeit des FinTS Protokolls zu implementieren.

2. **Error-Meldung MalformedMessage: HIRMG is mandatory but missing**

Das ist jetzt erstmal schwierig zu sagen woran das liegt. Da müsste man schon mehr Informationen haben. Ich habe aber zwei Vermutung woran es liegen könnte:
* Du hast das ganze wahrscheinlich so implementiert:
```javascript
client.EstablishConnection(function(error){
			if(error){
				console.log("Fehler: "+error);
			}else{
			client.MsgGetKontoUmsaetze(client.konten[0].sepa_data,null,null,function(error2,rMsg,data){
					});
			client.MsgGetKontoUmsaetze(client.konten[1].sepa_data,null,null,function(error2,rMsg,data){
						client.MsgEndDialog(function(error,recvMsg2){
							// 6. Secure Daten im Objekt aus dem Ram löschen
							client.closeSecure();
							console.log("ENDE");
						});
					});
			}
});
```
Das Problem ist, dass die HTTP-Requests letztlich Parallel ausgeführt werden und nicht wie nötig sequenziell, siehe dazu oben den dies betreffenden Abschnitt.

* Sequenzielle Implementierung aber ausversehen jedesmal `client.MsgEndDialog(…)` aufgerufen.
Trotz sequenzieller Implementierung hast du ausversehen im Callback den Dialog beendet durch den Aufruf der Methode `client.MsgEndDialog(…)`
Hilft das nicht, kannst du versuchen ob es daran liegt, dass nur das erste Konto das Abrufen der Umsätze mit diesem Segment HKKAZ erlaubt, die anderen eventuell nicht. Das findest du raus indem du pro Dialog die Umsätze nur für jeweils eines der Konten abrufst.
Hilft das auch nicht, hilft es zu debuggen oder die loggs einzuschalten. Wie das geht siehst du im Readme.

Gerne kannst du nochmal auf mich zu kommen wenn du nicht weiter kommst.

Viele Grüße
Jens

**Comment by fbrinker** [comment]
Vielen vielen Dank. Jetzt habe ich das Gesamtkonzept auch besser verstanden. Muss ja zugeben, dass ich die Menge an Dokus natürlich nur überfliegen konnte. Deine Informationen waren aber für das Verständnis Gold wert. 

Wenn die Nachrichten nur sequentiell abgearbeitet werden, macht das Verhalten natürlich Sinn und ja, mein Fehler kommt, wie von dir richtig erkannt, durch das zu frühe schließen der Verbindung. Dachte in dem Fall ich muss damit jede Anfrage beenden :) 

Eine sync Lib ist nicht immer eine Lösung, hatte bereits, je nach System, schonmal Probleme das keine Binaries zur Verfügung standen (für npms die diese direkt ausliefern) , würde hier aber natürlich etwas Übersicht bei vielen anfragen schaffen, das stimmt. Allerdings wird man ja meistens nur 1 bis 5 Konten abfragen und das dann auch automatisiert, so dass man das chaining nicht zwangsweise per Hand schreiben muss. Ich werde das nochmal etwas testen und mal schauen was sich da so ergibt :) 

Vielen Dank für die detaillierten Informationen!

**Comment by fbrinker** [comment]
Okay Async sieht gut aus, mit Fiber und irgend einer anderen hatte ich mal schlechte Erfahrungen gemacht :)

**Comment by fbrinker** [comment]
Nachtrag, kurz geteilt:

Nun klappt es wie gewünscht. Ich kann alle Konten durchlaufen und entsprechend die Daten holen.

```
async.eachSeries(
    client.konten,
    function (account, callback) {
        if (account && account.sepa_data && account.sepa_data.is_sepa) {
            client.MsgGetKontoUmsaetze(account.sepa_data, null, null, function (err, rMsg, data) {
                if (err) {
                    return console.log("Error while fetching the activities for " + account.konto_nr + ": " + err);
                }

                // do sth, dump to file, whatever
                callback();
            });
        } else {
            callback();
        }
    },
    function (err) {
        client.MsgEndDialog(function (error, recvMsg2) {
            client.closeSecure();
            console.log('End');
        });
    }
);
```

Dafür bietet sich ausgezeichnet `async.eachSeries` an.
... und ich schließe nun die Verbindung auch erst wirklich am Ende... :relaxed: :wink: 

 Danke für die Unterstützung und den Hinweis auf [async](https://github.com/caolan/async#eacharr-iterator-callback) :+1:

**Comment by jschyma** [comment]
Super das hört sich ja gut an.
Freut mich, dass ich dir helfen konnte.
Wie du vielleicht schon bemerkt hast, habe ich gleich mal das Readme angepasst um auf die sequentielle Abarbeitung hinzuweisen und Async dafür zu empfehlen. Eine interne Queue in der Library wie oben vorgeschlagen, davon bin ich wieder abgekommen. Das würde bestimmte Konstellationen der Aufrufe eventuell unmöglich machen. Alternativ habe ich mir überlegt eine Exception zu schmeißen wenn versucht wird eine neue Nachricht zu senden obwohl die letzte noch garnicht vom Server beantwortet wurde. Ich denke das ist der richtige Weg für die API.
Daher auch Danke für deine Anregung zu diesem Thema.
Viele Grüße 
Jens

**Comment by fbrinker** [comment]
Eine feste Queue ist vermutlich auch nicht so sinnvoll, man könnte aber überlegen bspw. obigen code snippet von mir als fertige methode anzubieten. Quasi als Methode um von der Verbindung / von dem Bank-Account alle Konten abzufragen (wie auch immer man die Daten dann zurück gibt, bei mir landen Sie aktuell in Dump-Dateien je Konto).
