### ISSUE TITLE
Fehlender Callback-Aufruf

### ISSUE THREAD

**Issue by fbrinker** [jschyma/open_fints_js_client#12]
Hallo,

ich habe beim Aufbauen von Verbindungen mit fehlerhaften Daten herausgefunden, das diese nicht abgefangen werden bzw ein Callback-Aufruf fehlt. Habe das ganze mal ergänzt und reiche in kürze den PR ein. 

War mir nicht so ganz sicher ob das alles nun so zu dem gedachten Stil passt, aber dafür ist es ja erstmal nur ein PR ;)

**Comment by jschyma** [comment]
Hallo,
ich habe mir dein Pullrequest angeschaut.
Ich verstehe allerdings nicht recht weshalb das überhaupt auftreten kann.
Was für fehlerhafte Daten?
Und eigentlich ist ja schon ein try - catch - block drum, der dann die Exception fängt wenn HIRMS == null ist, weil HIRMS.getEl nicht geht. Dann müsste der Callback auch gerufen werden, gut mit dem error="getEl kann von null nicht gerufen werden" aber bisher hatte ich zumindest immer gedacht, dass könnte nur dann passieren, wenn ein Fehler in der Implementierung des Protokolls ist und daher, dachte ich brauch ich keine extra Fehler Beschreibung.
Aber ambesten du sagst kurz wie man das Problem reproduzieren kann und welche fehlerhaften Daten du meinst.

**Comment by fbrinker** [comment]
Habe den PR aktualisiert, da hast du natürlich recht, das war etwas doppelt ... nur der Callback fehlte, den ich ja bereits ergänzt hatte. 

Lässt sich relativ einfach nachstellen: Frag mal bei einer Bank mit falschen Zugangsdaten an :relaxed:

**Comment by jschyma** [comment]
Okay hab ich gemerkt.
Ursprünglich dachte ich jetzt, versuche ich die Fälle abzufangen in dem falsche Zugangsdaten zurückgemeldet werden und eine ordentliche Exception an den Callback zu übergeben aber das hat sich als zu kompliziert herausgestellt vgl. Pullrequest.

Mit dem Pullrequest sollte der Fehler dann behoben sein.
