### ISSUE TITLE
Test mit einer echten Bank (Sparkasse)

### ISSUE THREAD

**Issue by Alesfatalis** [jschyma/open_fints_js_client#5]
Welche Schritte sind nötig um einen Test mit einer echten Bank durchzuführen die die Version 2.2 verwendet? Dies war mein Versuch:
![image](https://cloud.githubusercontent.com/assets/4603565/6288386/ed5e15dc-b918-11e4-87da-dfd2cf806356.png)
Daraus ergibt sich folgende Bankenliste:
```javascript
var bankenliste = {
    '60250010':{'blz':60250010,'url':"i009.bw.s-hbci.de"}};
```

Zusätzlich habe ich in ```\node_modules\open-fin-ts-js-client\lib\FinTSClient.js``` diese Zeile verändert:
```javascript
me.proto_version		= 220;// 300=FinTS;220=HBCI 2.2
```
Code in app.js:
```javascript
var FinTSClient = require("open-fin-ts-js-client");
var bankenliste = {
    '60250010':{'blz':60250010,'url':"i009.bw.s-hbci.de"}
};
var client = new FinTSClient(60250010,"Mein Anmeldename","Online PIN",bankenliste);
client.EstablishConnection(function(error){
    if(error){
        console.log("Fehler: "+error);
    }else{
        console.log("Erfolgreich Verbunden");
        client.MsgGetKontoUmsaetze(client.konten[0].sepa_data,null,null,function(error2,rMsg,data){
            if(error){
                console.log("Fehler beim laden der UmsÃ¤tze: "+error2);
            }else{
                console.log(JSON.stringify(data));
                client.MsgEndDialog(function(error,recvMsg2){
                    client.closeSecure();
                    console.log("ENDE");
                });
            }
        });
    }
});
```
Führt zu keinem Ergebnis app.js wird ausgeführt aber die Konsole bleibt leer? Habe ich etwas übersehen oder ist mir ein Denkfehler unterlaufen?

**Comment by jschyma** [comment]
Zunächst einmal vielen Dank für das Interesse an der API.
Folgende Dinge sind zu beachten:

  * Als URL ist die volle Adresse aus der Spalte PIN/TAN URL zu verwenden.
  * In FinTSClient..js muss nichts geändert werden. Den Versionswert auf 300 lassen, dieser wird automatisch auf 220 geändert wenn die betreffende Bank kein FinTS sondern nur HBCI2.2 unterstützt.
  * Kontounsätze laden wird nicht funktionieren, da Sparkassen den Geschäftsvorfall  HKKAZ nicht unterstützen. Der alternative Geschäftsvorfall  HKCAZ  ist noch nicht implementiert aber geplant.
  * Es bleibt übrig Kontosalden abzurufen.

Es macht auch Sinn das Logging einzuschalten, wie das funktioniert sieht  man im Readme unter Logging.

Ich hoffe ich konnte weiterhelfen, sollte es noch Schwierigkeiten geben stehe ich gerne für Fragen zur Verfügung.

**Comment by Alesfatalis** [comment]
Ja Sie konnten mir weiterhelfen. Die Abfrage der Kontosalden funktioniert jetzt bestens. Vielen Dank!
